### PR TITLE
[#5] Update SDK to v1.0.0-rc.6

### LINKED ISSUE #5: Update SDK to v1.0.0-rc.6
Also consider rebase on upstream

### PR DESCRIPTION
**Pull request by KirillovDenis**
This is draft because test fails on [dev-env master](https://github.com/nspcc-dev/neofs-dev-env). It seems the problem in storage nodes

close #5

### CODE REVIEW

**Comment by alexvanin** [comment]
Wait for https://github.com/nspcc-dev/neofs-node/issues/1577

**Comment by KirillovDenis** [comment]
Currently, tests passed. With the following fixes:
* https://github.com/nspcc-dev/neofs-node/pull/1653
* https://github.com/nspcc-dev/neofs-node/pull/1656

everything seems ok.

**Comment by carpawell** [comment]
#5 also says:

> Also consider rebase on upstream

Was it done? Or it's not worth it?

**Comment by KirillovDenis** [comment]
It was done at that point of time where PR was created.

**Review by carpawell — APPROVED** [review]

**Pull request merged**
